[general]
static=yes
writeprotect=no
[from-zadarma]
exten => _X.,1,NoOp(Appel entrant recu de Zadarma)
same => n,Answer()
same => n,Set(NUM=000000000000${CALLERID(num)})
same => n,Set(PADDED_NUM=${NUM:-12})
same => n,Set(CALL_UUID=11111111-2222-3333-4444-${PADDED_NUM})
same => n,AudioSocket(\${CALL_UUID},127.0.0.1:9090)
same => n,Hangup()
[from-internal]
exten => 500,1,NoOp(Appel test entrant depuis le softphone)
same => n,Answer()
same => n,Set(NUM=000000000000${CALLERID(num)})
same => n,Set(PADDED_NUM=${NUM:-12})
same => n,Set(CALL_UUID=11111111-2222-3333-4444-${PADDED_NUM})
same => n,AudioSocket(\${CALL_UUID},127.0.0.1:9090)
same => n,Hangup()