[general]
static=yes
writeprotect=no

[from-external]
; Contexte pour FlyNumber et Zadarma Inbound
exten => _X.,1,NoOp(Appel entrant sur DID: ${EXTEN})
same => n,Answer()
same => n,Set(DID_PART=${EXTEN:-8})
same => n,Set(NUM=000000000000${CALLERID(num)})
same => n,Set(PADDED_NUM=${NUM:-12})
same => n,Set(CALL_UUID=${DID_PART}-2222-3333-4444-${PADDED_NUM})
same => n,AudioSocket(${CALL_UUID},127.0.0.1:9090)
same => n,Hangup()

[from-internal]
exten => 500,1,NoOp(Appel test entrant depuis le softphone)
same => n,Answer()
same => n,Set(DID_PART=00000000)
same => n,Set(NUM=000000000000${CALLERID(num)})
same => n,Set(PADDED_NUM=${NUM:-12})
same => n,Set(CALL_UUID=${DID_PART}-2222-3333-4444-${PADDED_NUM})
same => n,AudioSocket(${CALL_UUID},127.0.0.1:9090)
same => n,Hangup()

; Route pour passer des appels via Zadarma
[outbound-zadarma]
exten => _X.,1,NoOp(Appel sortant vers ${EXTEN} via Zadarma)
same => n,Dial(PJSIP/${EXTEN}@zadarma_endpoint)
same => n,Hangup()