[general]
static=yes
writeprotect=no
[from-zadarma]
exten => _X.,1,NoOp(Appel entrant recu de Zadarma)
same => n,Answer()
; On utilise un UUID fixe pour que AudioSocket soit content
same => n,Set(CALL_UUID=69a68697-a77a-42c6-b51c-ed0c0d0d0d0d)
same => n,AudioSocket(\${CALL_UUID},127.0.0.1:9090)
same => n,Hangup()
[from-internal]
exten => 500,1,NoOp(Appel test entrant depuis le softphone)
same => n,Answer()
; On utilise un UUID fixe pour que AudioSocket soit content
same => n,Set(CALL_UUID=69a68697-a77a-42c6-b51c-ed0c0d0d0d0d)
same => n,AudioSocket(\${CALL_UUID},127.0.0.1:9090)
same => n,Hangup()