[global]
type=global
user_agent=Asterisk PBX

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=76.13.1.190
external_signaling_address=76.13.1.190

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

; --- CONFIGURATION FLYNUMBER (INBOUND) ---
[flynumber_identify]
type=identify
endpoint=flynumber_endpoint
match=46.19.209.14, 46.19.210.14

[flynumber_endpoint]
type=endpoint
context=from-external
disallow=all
allow=ulaw,alaw
aors=flynumber_aor

[flynumber_aor]
type=aor
contact=sip:46.19.209.14:5060

; --- CONFIGURATION ZADARMA (OUTBOUND) ---
[zadarma_registration]
type=registration
outbound_auth=zadarma_auth
server_uri=sip:sip.zadarma.com
client_uri=sip:48573@sip.zadarma.com
retry_interval=60

[zadarma_auth]
type=auth
auth_type=userpass
username=48573
password=${ZADARMA_PASSWORD}

[zadarma_endpoint]
type=endpoint
context=from-external
disallow=all
allow=ulaw,alaw
outbound_auth=zadarma_auth
aors=zadarma_aor

[zadarma_aor]
type=aor
contact=sip:sip.zadarma.com:5060

[zadarma_identify]
type=identify
endpoint=zadarma_endpoint
match=sip.zadarma.com

; --- EXTENSION INTERNE ---
[100]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=100
aors=100
rtp_symmetric=yes
rewrite_contact=yes
force_rport=yes

[100]
type=auth
auth_type=userpass
password=123456
username=100

[100]
type=aor
max_contacts=5
